### ISSUE TITLE
omx.R needs to be updated

### ISSUE THREAD

**Issue by bstabler** [gregmacfarlane/omxr#1]
It looks like your omx.R is out-of-date.  Please start with the latest version since I've made a number of improvements.  Thanks.

**Comment by gregmacfarlane** [comment]
Ah, darnit. I thought I had gotten the latest version before starting. I will examine this next week.

**Comment by gregmacfarlane** [comment]
@bstabler Are there any other planned improvements beyond those in the [commit history](https://github.com/osPlanning/omx/commits/dev/api/r/omx.R)? I see chunking and R 3.x issues; any others planned?

**Comment by gregmacfarlane** [comment]
@bstabler I think I've updated the code to match changes I have seen in the [commit history](https://github.com/osPlanning/omx/commits/dev/api/r/omx.R). Anything else?
