### ISSUE TITLE
Switch parameter order

### ISSUE THREAD

**Issue by josiekre** [gregmacfarlane/omxr#12]
https://github.com/gregmacfarlane/omxr/blob/4c093f2d675c1395937e533a452cdb0d49319638/R/read_write_omx.R#L308

I tried to make this commit without cloning the repo but to no avail. The `long = TRUE` parameter needs to be last in the list for the function call to work as `omxr::write_all_omx(data, "path/to/output.omx")`.

**Comment by gregmacfarlane** [comment]
Good point.
