### ISSUE TITLE
How do you figure out what tables are in the omx file?

### ISSUE THREAD

**Issue by josiekre** [gregmacfarlane/omxr#3]
I received an omx file from someone else without specification of what the tables inside it are called. How do I figure out how to read the file in without these?

**Comment by josiekre** [comment]
Nevermind.

    rhdf5::h5ls("simple.omx")

It might be helpful to include the output in the vignette. Maybe it is included when actually run, but right now I'm just reading the raw Rmd because I can't figure out how to call it with `vignette()`.

**Comment by gregmacfarlane** [comment]
For completeness, the package includes a `list_omx()` function that returns a list of the OMX contents.
